//
//  AssetString.swift
//  Peach
//
//  Created by Василий on 05.09.2023.
//

import Foundation

enum AssetString: String {
    case calendar = "calendar"
    case assistant = "assistant"
    case profile = "profile"
    case underDevelopment = "underDevelopment"
    case private_assistant = "private_assistant"
    case health_report = "health_report_pdf"
    case premiumAccount = "premiumAccount"
    case premiumGreetings = "premiumGreetings"
    case checkOut = "checkOut"
    case askQuestion = "askQuestion"
    case save = "save"
    case changeDate = "changeDate"
    case exit = "exit"
    case track_your_cycle = "track_your_cycle"
    case track_your_symptoms = "track_your_symptoms"
    case convenient_calendar = "convenient_calendar"
    case assistant_will_answer = "assistant_will_answer"
    case share_symptoms = "share_symptoms"
    case goContinue = "continue"
    case skip = "skip"
    case connectPreemium = "connectPreemium"
    case first_quiestions_free = "first_quiestions_free"
    case step_one = "step_one"
    case step_two = "step_two"
    case step_three = "step_three"
    case lets_meet = "lets_meet"
    case when_cycle_started = "when_cycle_started"
    case what_is_your_name = "what_is_your_name"
    case how_old_are_you = "how_old_are_you"
    case select_date = "select_date"
    case cycle_duration = "cycle_duration"
    case ok = "ok"
    case fill_all_fields = "fill_all_fields"
    case done = "done"
    case select_subscription = "select_subscription"
    case symptoms = "symptoms"
    case discharge = "discharge"
    case normal = "normal"
    case headache = "headache"
    case fatigue = "fatigue"
    case pimples = "pimples"
    case pain_in_the_lower_abdomen = "pain_in_the_lower_abdomen"
    case bloating = "bloating"
    case nausea = "nausea"
    case food_cravings = "food_cravings"
    case constipation = "constipation"
    case diarrhea = "diarrhea"
    case itching_in_the_vagina = "itching_in_the_vagina"
    case no_discharge = "no_discharge"
    case with_blood = "with_blood"
    case sticky = "sticky"
    case watery = "watery"
    case white = "white"
    case light = "light"
    case medium = "medium"
    case strong = "strong"
    case blood_clots = "blood_clots"
    case my_symptoms = "my_symptoms"
    case profuse_bleeding = "profuse_bleeding"
    case add_symptom = "add_symptom"
    case write_smth = "write_smth"
    case ask_question = "ask_question"
    case ask_ten_questions_free = "ask_ten_questions_free"
    case personal_assistant = "personal_assistant"
    case mark_symptoms = "mark_symptoms"
    case me = "me"
    case limitQuestionsIsOver = "limitQuestionsIsOver"
    case period = "period"
    case change_period_date = "change_period_date"
    case ovulation = "ovulation"
    case mark_your_period = "mark_your_period"
    case cancel = "cancel"
    
    case enter_age = "enter_age"
    case select_birth_date = "select_birth_date"
    case invalid_age = "invalid_age"
    case age_input_method = "age_input_method"
    case manual_input = "manual_input"
    case date_selection = "date_selection"
    case warning = "warning"
    case age_restriction = "age_restriction"
    
    var text: String {
        return NSLocalizedString(rawValue, comment: "")
    }
}
